---
# credited to Sergey Kalikin
# Source: https://stackoverflow.com/questions/75343804/better-way-to-install-helm-with-ansible

- name: Download Helm command line tool
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    return_content: true
  register: helm_installer  # Register the downloaded script content

- name: Install Helm
  ansible.builtin.command:
    cmd: bash
    stdin: "{{ helm_installer.content }}"
    creates: /usr/local/bin/helm  # Ensure Helm is only installed if not already present
  environment:
    DESIRED_VERSION: "{{ helm_version | default('') }}"  # Use the desired version of Helm if specified
