---
# Common tasks that are prerequisites for other roles

- name: Include vault secrets
  ansible.builtin.include_vars:
    file: secrets.yaml
  no_log: true  # Hide sensitve information

- name: Install pip/python requirements for Kubernetes
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-kubernetes
    state: present  # Ensure the packages are installed
