---
# Cert-Manager tasks

- name: Create cert-manager directory
  ansible.builtin.file:
    path: "{{ cert_manager_path }}"
    mode: '0644'  # Set directory permissions
    state: directory  # Ensure the directory exists

- name: Copy cloudflare-api-key-secret.yaml to the master node
  ansible.builtin.template:
    src: cloudflare-api-key-secret.yaml.j2
    dest: "{{ cert_manager_path }}/cloudflare-api-key-secret.yaml"
    mode: '0644'  # Set file permissions

- name: Copy clusterissuer-letsencrypt-cloudflare.yaml to the master node
  ansible.builtin.template:
    src: clusterissuer-letsencrypt-cloudflare.yaml.j2
    dest: "{{ cert_manager_path }}/clusterissuer-letsencrypt-cloudflare.yaml"
    mode: '0644'  # Set file permissions

- name: Add Cert-Manager Helm repository
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
    state: present  # Ensure repository is added
  environment:
    KUBECONFIG: "{{ kubectl_config }}"  # Use the kubectl config environment variable

- name: Create Cert-Manager namespace
  kubernetes.core.k8s:
    name: cert-manager
    api_version: v1
    kind: Namespace
    state: present  # Ensure the namespace exists
  environment:
    KUBECONFIG: "{{ kubectl_config }}"  # Use the kubectl config environment variable

- name: Create Cloudflare secret for Cert-Manager and Issuer
  kubernetes.core.k8s:
    state: present
    src: "{{ cert_manager_path }}/cloudflare-api-key-secret.yaml"
  environment:
    KUBECONFIG: "{{ kubectl_config }}"  # Use the kubectl config environment variable

- name: Deploy Cert-Manager chart inside cert-manager namespace
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: "{{ cert_manager_chart_ref }}"
    chart_version: "{{ cert_manager_chart_version }}"
    release_namespace: cert-manager
    update_repo_cache: true
    create_namespace: true
    state: present
    wait: true
    values:
      installCRDs: true  # Additional values to install CRDs
  environment:
    KUBECONFIG: "{{ kubectl_config }}"  # Use the kubectl config environment variable

- name: Create Cert-Manager Issuer
  kubernetes.core.k8s:
    state: present
    src: "{{ cert_manager_path }}/clusterissuer-letsencrypt-cloudflare.yaml"
  environment:
    KUBECONFIG: "{{ kubectl_config }}"  # Use the kubectl config environment variable
